// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_uZqw83p_L2blsICfyvwh3jQ1SJnwmEM',
    appId: '1:876934993940:web:1068f207fbd1675f4cef01',
    messagingSenderId: '876934993940',
    projectId: 'swapapp-44a7d',
    authDomain: 'swapapp-44a7d.firebaseapp.com',
    storageBucket: 'swapapp-44a7d.firebasestorage.app',
    measurementId: 'G-N821EEG8HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb-gzq9wvDxZpNW6Myq1yYmW8uqwDhoI8',
    appId: '1:876934993940:android:7021dde3a19463f14cef01',
    messagingSenderId: '876934993940',
    projectId: 'swapapp-44a7d',
    storageBucket: 'swapapp-44a7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Nu1QpPYlLNnkRvq3Ov_2S4sWt35W34k',
    appId: '1:876934993940:ios:2f4faeeb70f118944cef01',
    messagingSenderId: '876934993940',
    projectId: 'swapapp-44a7d',
    storageBucket: 'swapapp-44a7d.firebasestorage.app',
    iosBundleId: 'com.example.swapapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Nu1QpPYlLNnkRvq3Ov_2S4sWt35W34k',
    appId: '1:876934993940:ios:2f4faeeb70f118944cef01',
    messagingSenderId: '876934993940',
    projectId: 'swapapp-44a7d',
    storageBucket: 'swapapp-44a7d.firebasestorage.app',
    iosBundleId: 'com.example.swapapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_uZqw83p_L2blsICfyvwh3jQ1SJnwmEM',
    appId: '1:876934993940:web:adba58ca718512fd4cef01',
    messagingSenderId: '876934993940',
    projectId: 'swapapp-44a7d',
    authDomain: 'swapapp-44a7d.firebaseapp.com',
    storageBucket: 'swapapp-44a7d.firebasestorage.app',
    measurementId: 'G-LY797J3K7D',
  );
}
